interface preset {
	[key: string]: string;
}

export const basePresets: preset = {
	"브론즈": "*b",
	"브": "*b",
	"실버": "*s",
	"실": "*s",
	"골드": "*g",
	"골": "*g",
	"플래티넘": "*p",
	"플": "*p",
	"다이아몬드": "*d",
	"다이아": "*d",
	"다": "*d",
	"루비": "*r",
	"루": "*r",
	"브실": "*b..s",
	"실골": "*s..g",
	"브실골": "*b..g",
	"골플": "*g..p",
	"플다": "*p..d",
	"다루": "*d..r",

	"수학": "#math",
	"구현": "#implementation",
	"다이나믹프로그래밍": "#dp",
	"디피": "#dp",
	"dp": "#dp",
	"자료구조": "#data_structures",
	"자구": "#data_structures",
	"그래프": "#graphs",
	"문자열": "#string",
	"그리디": "#greedy",
	"브루트포스": "#bruteforcing",
	"브포": "#bruteforcing",
	"정수론": "#number_theory",
	"기하학": "#geometry",
	"세그먼트트리": "#segtree",
	"세그": "#segtree",
	"이분탐색": "#binary_search",
	"애드혹": "#adhoc",
	"조합론": "#combinatorics",
	"구성적": "#constructive",
	"파싱": "#parsing",
	"많은조건분기": "#case_work",
	"케이스워크": "#case_work",
	"케웍": "#case_work",
	"게임이론": "#game_theory",
	"게임": "#game_theory",
	"확률론": "#probability",
	"최대유량": "#flow",
	"유량": "#flow",
	"플로우": "#flow",
	"런타임전의전처리": "#precomputation",
	"전처리": "#precomputation",
	"임의정밀도": "#arbitrary_precision",
	"큰수": "#arbitrary_precision",
	"고속푸리에변환": "#fft",
	"fft": "#fft",
	"미적분학": "#calculus",
	"스프라그그런디정리": "#sprague_grundy",
	"그런디": "#sprague_grundy",

	"한국어": "lang:ko",
	"영어": "lang:en",
	"일본어": "lang:ja",
	"폴란드어": "lang:pl",

	"최근": "id:15000..",

	"브1": "*b1",
	"브2": "*b2",
	"브3": "*b3",
	"브4": "*b4",
	"브5": "*b5",
	"실1": "*s1",
	"실2": "*s2",
	"실3": "*s3",
	"실4": "*s4",
	"실5": "*s5",
	"골1": "*g1",
	"골2": "*g2",
	"골3": "*g3",
	"골4": "*g4",
	"골5": "*g5",
	"플1": "*p1",
	"플2": "*p2",
	"플3": "*p3",
	"플4": "*p4",
	"플5": "*p5",
	"다1": "*d1",
	"다2": "*d2",
	"다3": "*d3",
	"다4": "*d4",
	"다5": "*d5",
	"루1": "*r1",
	"루2": "*r2",
	"루3": "*r3",
	"루4": "*r4",
	"루5": "*r5",
};
